# Path
data_dir: /scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_done/
output_dir: /scratch/mrmn/brochetc/GAN_2D/Exp_Codebook/
mean_file: mean_with_8_var.npy        # file in data_dir  : Mean of variables (see compute_mean_max.py)  
max_file: max_with_8_var.npy          # file in data_dir  : Max = Max-Mean of variables (see compute_mean_max.py) 
id_file: IS_method_labels_8_var.csv   # file in data_dir  : labels ID file

# Path for experiments
SET_NUM: 2   # run test jobs in Set_2
pretrained_model: 0 # step at which pretrained model have been saved
which_experiment: -1 # index of the experiment to run if pretrained_model is activated # not really used anymore
max_relaunch: 0 # number of times we relaunch the expe after timeout
auto_relaunch: False # set to Yes if you want an automatic relaunch. Manual relaunch (e.g. from pretrained)                        should be passed with auto_relaunch=False to prevent overwriting previous results.
main_file: main_ddp.py # main_horovod.py
slurm_file: run_GAN.slurm # slurm file in slurm_dir (=home_dir + "/slurms/")
slurm_docker_run_perso: slurm-docker-run_perso-DDP # slurm file in home_dir

# PARAMETRES A TESTER: changer le lr et/ou le lr_mlp (ajouter un arg pour ça car pas pris en compte actuellement), 
#  scheduler sur lr (exp scheduler), 
#  channel_multiplier: tester 1 vs 2 vs 3
#  batch size : 4, 8, 32 (utiliser 512 latent dim!)

very_small_exp: False 
small_exp: False
normal_exp_steps: 5

ensemble:
  --epochs_num : [25]
  --batch_size: [32]
  --lr_D: [0.002]
  --lr_G: [0.002]
  --g_channels: [3]
  --d_channels: [3]
  --var_names: ["['u','v','t2m']"]
  --total_steps: [360000]
  --conditional: [True]
  --discrete_level: [0]
  --path_batch_shrink: [2]
  --model: ['stylegan2']
  --train_type: ['stylegan']
  --latent_dim: [512]
  --pretrained_model: [-1]
  --use_noise: [True]
  --crop_indexes: ["[78,206,55,183]"]
  --crop_size: ["[128,128]"]
  --full_size: ["[256,256]"]
  --channel_multiplier: [2] 
  
VQparams_file: '/home/mrmn/brochetc/aWeatherCodebook/configs/VQgan.yml'
