VQparams:
  ddconfig:
    double_z: false
    z_channels: 3
    resolution: 128
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult:
    - 1
    - 2
    - 4
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
  lossconfig:
    target: model.losses.vqperceptual.VQLPIPSWithDiscriminator
    params:
      disc_conditional: false
      disc_in_channels: 3
      disc_start: 500000
      disc_weight: 0.6
      codebook_weight: 1.0
  n_embed: 8192
  embed_dim: 3
  ckpt_path: '/scratch/mrmn/brochetc/GAN_2D/Exp_Codebook/VQ-GAN/EnDecoder_vqgan/checkpoints/gens_vqgan_fl4_D3_N8192_32x32x3_cyclic_3717.ckpt'